"""
Research Assistant Application

An intelligent research assistant that can:
- Search for information
- Perform calculations
- Read and write files
- Analyze data
- Generate reports

This application demonstrates the integration of:
- Chat Models (OpenAI)
- Agents (ReAct Agent)
- Tools (Calculator, Search, File Operations)
- Agent Executor
"""

import os
import sys
from datetime import datetime
from dotenv import load_dotenv

# Add src to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.chat_models import OpenAIChatModel
from src.tools import CalculatorTool, SearchTool, FileReadTool, FileWriteTool, FileListTool
from src.agents import ReActAgent, AgentExecutor

# Load environment variables
load_dotenv()


class ResearchAssistant:
    """Intelligent Research Assistant using Agents and Tools.
    
    This assistant can:
    - Answer questions using search
    - Perform calculations
    - Read and analyze files
    - Generate research reports
    - Save findings to files
    """
    
    def __init__(
        self,
        model_name: str = "gpt-3.5-turbo",
        temperature: float = 0.0,
        workspace_dir: str = "data/research"
    ):
        """Initialize the research assistant.
        
        Args:
            model_name: LLM model to use
            temperature: Temperature for generation
            workspace_dir: Directory for research files
        """
        # Check for API key
        if not os.getenv("OPENAI_API_KEY"):
            raise ValueError("OPENAI_API_KEY not found in environment variables")
        
        # Create workspace directory if it doesn't exist
        os.makedirs(workspace_dir, exist_ok=True)
        self.workspace_dir = workspace_dir
        
        # Initialize LLM
        self.llm = OpenAIChatModel(
            model_name=model_name,
            temperature=temperature
        )
        
        # Initialize tools
        self.tools = [
            CalculatorTool.create(),
            SearchTool.create(),
            FileReadTool.create(base_directory=workspace_dir),
            FileWriteTool.create(base_directory=workspace_dir),
            FileListTool.create(base_directory=workspace_dir),
        ]
        
        # Initialize agent
        self.agent = ReActAgent.create(
            llm=self.llm,
            tools=self.tools,
            verbose=True,
            max_iterations=10
        )
        
        # Initialize executor
        self.executor = AgentExecutor.create(
            agent=self.agent,
            tools=self.tools,
            max_iterations=10,
            verbose=True,
            return_intermediate_steps=True
        )
        
        print("✅ Research Assistant initialized!")
        print(f"📁 Workspace: {workspace_dir}")
        print(f"🔧 Available tools: {', '.join([tool.name for tool in self.tools])}\n")
    
    def research(self, task: str) -> dict:
        """Execute a research task.
        
        Args:
            task: The research task description
            
        Returns:
            Dictionary with output and intermediate steps
        """
        print(f"\n{'='*80}")
        print(f"  🔬 Research Task")
        print(f"{'='*80}")
        print(f"📋 Task: {task}\n")
        
        result = self.executor.run(task)
        
        print(f"\n{'='*80}")
        print(f"  ✅ Research Complete")
        print(f"{'='*80}\n")
        
        return result
    
    def generate_report(self, topic: str, findings: str) -> str:
        """Generate a research report.
        
        Args:
            topic: The research topic
            findings: The research findings
            
        Returns:
            Path to the generated report
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"research_report_{timestamp}.txt"
        
        report_content = f"""# Research Report: {topic}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Findings

{findings}

## Conclusion

This report was automatically generated by the Research Assistant.
"""
        
        # Save report
        filepath = os.path.join(self.workspace_dir, filename)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(report_content)
        
        print(f"📄 Report saved: {filepath}")
        return filepath


def demo_research_tasks():
    """Demonstrate various research tasks."""
    print("\n" + "="*80)
    print("  🚀 Research Assistant Demo")
    print("="*80 + "\n")
    
    try:
        # Initialize assistant
        assistant = ResearchAssistant(
            model_name="gpt-3.5-turbo",
            temperature=0.0,
            workspace_dir="data/research"
        )
        
        # Task 1: Simple calculation
        print("\n" + "="*80)
        print("  Task 1: Financial Calculation")
        print("="*80)
        
        task1 = """Calculate the compound interest on $10,000 invested at 5% annual rate for 3 years.
Use the formula: A = P(1 + r)^t where P=10000, r=0.05, t=3.
Then save the result to a file called investment_calculation.txt"""
        
        result1 = assistant.research(task1)
        print(f"\n📊 Result: {result1['output']}")
        
        # Task 2: Information search and file operations
        print("\n" + "="*80)
        print("  Task 2: Research and Documentation")
        print("="*80)
        
        task2 = """Search for information about Python programming language.
Then create a summary file called python_summary.txt with the key points."""
        
        result2 = assistant.research(task2)
        print(f"\n📊 Result: {result2['output']}")
        
        # Task 3: File analysis
        print("\n" + "="*80)
        print("  Task 3: File Analysis")
        print("="*80)
        
        task3 = """List all files in the current directory and create a summary of what files exist."""
        
        result3 = assistant.research(task3)
        print(f"\n📊 Result: {result3['output']}")
        
        # Generate final report
        print("\n" + "="*80)
        print("  📝 Generating Final Report")
        print("="*80 + "\n")
        
        findings = f"""
Task 1 - Financial Calculation:
{result1['output']}

Task 2 - Research and Documentation:
{result2['output']}

Task 3 - File Analysis:
{result3['output']}
"""
        
        report_path = assistant.generate_report(
            topic="Research Assistant Demo Tasks",
            findings=findings
        )
        
        print(f"\n✅ All tasks completed!")
        print(f"📄 Final report: {report_path}\n")
        
    except ValueError as e:
        print(f"\n❌ Configuration Error: {str(e)}")
        print("Please set OPENAI_API_KEY in your .env file\n")
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        import traceback
        traceback.print_exc()


def interactive_mode():
    """Run the assistant in interactive mode."""
    print("\n" + "="*80)
    print("  💬 Research Assistant - Interactive Mode")
    print("="*80)
    print("\nCommands:")
    print("  - Describe your research task")
    print("  - Type 'quit' or 'exit' to end")
    print("  - Type 'help' for examples")
    print("\n" + "="*80 + "\n")
    
    try:
        assistant = ResearchAssistant()
        
        while True:
            try:
                task = input("\n🔬 Research Task: ").strip()
                
                if not task:
                    continue
                
                if task.lower() in ['quit', 'exit', 'q']:
                    print("\n👋 Goodbye!\n")
                    break
                
                if task.lower() == 'help':
                    print("\n📖 Example Tasks:")
                    print("  1. Calculate 15% of 250 and save to results.txt")
                    print("  2. Search for information about AI and summarize it")
                    print("  3. List all files and create an inventory")
                    print("  4. Read data.txt and analyze the content\n")
                    continue
                
                result = assistant.research(task)
                print(f"\n✅ Result: {result['output']}\n")
                
            except KeyboardInterrupt:
                print("\n\n👋 Goodbye!\n")
                break
            except Exception as e:
                print(f"\n❌ Error: {str(e)}\n")
    
    except ValueError as e:
        print(f"\n❌ Configuration Error: {str(e)}")
        print("Please set OPENAI_API_KEY in your .env file\n")


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Research Assistant Application")
    parser.add_argument(
        '--mode',
        choices=['demo', 'interactive'],
        default='demo',
        help='Run mode: demo (run example tasks) or interactive (chat mode)'
    )
    
    args = parser.parse_args()
    
    if args.mode == 'demo':
        demo_research_tasks()
    else:
        interactive_mode()


if __name__ == "__main__":
    main()

# Made with Bob
